name: Reviews
on: 
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]


jobs:
  check_review_requirements:
    runs-on: ubuntu-latest
    name: Check Review Requirements
    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4
      - name: Check Review Requirements
        uses: ./.github/actions/label-based-review-requirements
        with:
          token: ${{ secrets.GITHUB_TOKEN }}