name: Reviews
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check_review_requirements:
    runs-on: ubuntu-latest
    name: Check Requirements
    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4
      - name: Check Review Requirements
        uses: ./.github/actions/label-based-review-requirements
        with:
          token: ${{ secrets.GITHUB_TOKEN }}