name: Reviews-Trigger
on: 
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
    call-workflow:
        uses: ./.github/workflows/review-requirements.yml